### ISSUE TITLE
Allow label to set html

### ISSUE THREAD

**Issue by andrewdavidcostello** [metrisk/react_metrisk-components#41]
We have a requirement on S2R to allow html in a checkbox label therefore we need to update the Field component to allow dangerous setting of html.

https://github.com/metrisk/react_metrisk-components/blob/master/src/components/Field/Field.tsx

A story example should be added to support the use case.

**Comment by H-Walker-01** [comment]
This is already implemented ```## Custom Label
You can pass a component to the label prop.

<Preview>
  <Story name='Label'>
    {() => {
      const [value, setValue] = useState('')
      return (
        <Field id={'field'} label={<div>Custom label!</div>} type={'text'} value={value} onChange={setValue} />
      )
    }}
  </Story>
</Preview>``` using ` if (React.isValidElement(label)) return label`

**Comment by H-Walker-01** [comment]
let me know if this was what you meant and if so we can close this 👍

**Comment by andrewdavidcostello** [comment]
Yeah I've just used a custom label element now, good spot!

**Comment by andrewdavidcostello** [comment]
This does work but it does not retain the error state on the label element, we need to make sure it still adds the label classes to the element or simply allows custom content within the label element itself.

`if (React.isValidElement(label)) return label`

Is in Field and FieldPicker, need to ensure both allow for:

```
className={cx(props.inline && 'label--inline m m--r-md', state === 'Error' && `label${states[state]}`)}
```

Or we pass through the state to the valid element.
